create table datos_intra_operatorios(
id varchar(255) primary key, 
induccionpropofol NUMERIC(4,1) not null,
inducciondexmedetomidina NUMERIC(4,1) not null, 
induccionLidocaina NUMERIC(4,1) not null,
induccionKetamina NUMERIC(4,1) not null,
mantenimientopropofol NUMERIC(4,1) not null,
mantenimientoDexmedetomidina NUMERIC(4,1) not null,
mantenimientoLidocaina NUMERIC(4,1) not null,
mantenimientoKetamina NUMERIC(4,1) not null,
despertar integer not null, 
tiempoqx integer not null, 
presionarterial boolean not null, 
valorpresionarterial varchar(50),
frecuenciacardiaca boolean not null, 
valorfrecuenciacardiaca varchar(50), 
frecuenciarespiratoria boolean not null, 
valorfrecuenciarespiratoria varchar(50),
co2 boolean not null, 
valorco2 varchar(50),
sato2 boolean not null, 
valorsato2 varchar(50),
created_at TIMESTAMP
);